version: '3.8'

services:
  bot:
    build: .
    container_name: cards-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./Data:/app/Data
      - ./Images:/app/Images
      - ./Messages:/app/Messages
